# Generated by Django 3.2.11 on 2022-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название штата')),
                ('zip_code', models.CharField(max_length=2, unique=True, verbose_name='Почтовый код')),
                ('capital', models.CharField(max_length=50, verbose_name='Столица штата')),
                ('largest_city', models.CharField(max_length=50, verbose_name='Крупнейший город')),
                ('ratification', models.DateTimeField(verbose_name='Дата присоединения')),
                ('population', models.IntegerField(verbose_name='Население')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь, кв.км')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь суши,кв.км')),
                ('water_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь воды, кв.км')),
            ],
        ),
    ]
