# Generated by Django 3.2.11 on 2022-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='ratification',
            field=models.DateField(verbose_name='Дата присоединения'),
        ),
    ]
