# Generated by Django 3.2.11 on 2022-01-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_state_land_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='largest_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Крупнейший город'),
        ),
    ]
