# Generated by Django 3.2.11 on 2022-01-09 13:09

from django.db import migrations
import csv


def csv_to_db(apps, schema_editor):
    State = apps.get_model('main', 'State')
    with open('us_states.csv') as f:
        reader = csv.DictReader(f)
        for row in reader:
            State.objects.get_or_create(name=row['Name'],
                                 zip_code=row['ZIP code'],
                                 capital=row['Capital'],
                                 largest_city=row['Largest city'],
                                 ratification=row['Ratification or Admission'],
                                 population=row['Population'],
                                 total_area=row['Total area, km2'],
                                 land_area=row['Land area, km2'],
                                 water_area=row['Water area, km2'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_state_largest_city'),
    ]

    operations = [
        migrations.RunPython(csv_to_db),
    ]
