# Generated by Django 3.2.11 on 2022-01-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_data_csv_to_db_20220109_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Флаг'),
        ),
        migrations.AddField(
            model_name='state',
            name='seal_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Печать'),
        ),
    ]
