# Generated by Django 3.2.11 on 2022-01-11 14:31

from django.db import migrations


def fill_largest_city(apps, schema_editor):
    State = apps.get_model('main', 'State')
    for state in State.objects.filter(largest_city=''):
        state.largest_city=state.capital
        state.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220110_2233'),
    ]

    operations = [
        migrations.RunPython(fill_largest_city),
    ]
