# Generated by Django 3.2.11 on 2022-01-16 08:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220116_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='flag_image',
            field=models.FileField(blank=True, null=True, upload_to=main.models.flag_directory_path, verbose_name='Флаг'),
        ),
    ]
