# Generated by Django 3.2.11 on 2022-01-16 08:57

from django.db import migrations
from main.models import flag_directory_path, seal_directory_path 


def fill_flags_seals(apps, schema_editor):
    State = apps.get_model('main', 'State')
    # State.objects.update_or_create(flag_image=flag_directory_path(obj,filename=False),
    #                                 seal_image=seal_directory_path)
    for state in State.objects.all():
        if not state.seal_image:
            state.flag_image=flag_directory_path(state, filename=False)
        if not state.seal_image:
            state.seal_image=seal_directory_path(state, filename=False)
        state.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_state_flag_image'),
    ]

    operations = [
        migrations.RunPython(fill_flags_seals),
    ]
